<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_alokasi_anggaran_covid_model extends CI_Model
{

    public $table = 'm_alokasi_anggaran_covid';
    public $id = 'id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
    $this->db->like('id', $q);
	$this->db->or_like('id_satker', $q);
    $this->db->or_like('kegiatan', $q);
	$this->db->or_like('alokasi', $q);
    $this->db->or_like('tahap', $q);
	$this->db->or_like('create_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
    $this->db->select(''.$this->table.'.*,m_satker.nama,m_kegiatan_anggaran_covid.nama_kegiatan,m_sub_kegiatan_anggaran_covid.nama_sub_kegiatan,m_output_anggaran_covid.nama_output');
    $this->db->order_by('id_satker', $this->order);
    $this->db->order_by('kegiatan', 'ASC');
    $this->db->order_by('id_sub_kegiatan', 'ASC');
    $this->db->order_by('level', 'ASC');
    //$this->db->order_by('id_output', $this->order);/
    if($_SESSION['id_user_level'] == 3 OR $_SESSION['id_user_level'] == 4 ){
            //$whereSatker = 'AND mac.id_satker = "'.$_SESSION['id_satker'].'" ';
            $this->db->where('m_alokasi_anggaran_covid.id_satker',$_SESSION['id_satker']);
    }
    //$this->db->like(''.$this->table.'.id', $q);
    if(!empty($q)){
	$this->db->like('m_satker.nama', $q);
    }
    //$this->db->or_like('kegiatan', $q);
	//$this->db->or_like('alokasi', $q);
    //$this->db->or_like('tahap', $q);
	//$this->db->or_like('create_date', $q);
    $this->db->join('m_satker','m_satker.id_satker = '.$this->table.'.id_satker');
    $this->db->join('m_kegiatan_anggaran_covid','m_kegiatan_anggaran_covid.id = '.$this->table.'.kegiatan','left');
    $this->db->join('m_sub_kegiatan_anggaran_covid','m_sub_kegiatan_anggaran_covid.id = '.$this->table.'.id_sub_kegiatan','left');
    $this->db->join('m_output_anggaran_covid','m_output_anggaran_covid.id = '.$this->table.'.id_output','left');
	//$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();

        //echo '<br><br><br><br>'.$this->db->last_query();
    }

    function pagu_digunakan($param){
        $this->db->select('SUM(m_alokasi_anggaran_covid.alokasi_akhir) as pagu_digunakan,alokasi_akhir');
        $this->db->from('m_alokasi_anggaran_covid');
        // if(!empty($param['id_satker']))
        //  $this->db->where('m_alokasi_anggaran_covid.id_satker',$param['id_satker']);
        // if(!empty($param['kegiatan']))
        //  $this->db->where('m_alokasi_anggaran_covid.kegiatan',$param['kegiatan']);
        // if(!empty($param['id_sub_kegiatan']))
        //  $this->db->where('m_alokasi_anggaran_covid.id_sub_kegiatan',$param['id_sub_kegiatan']);

        //  $this->db->where('m_alokasi_anggaran_covid.level',($param['level'] + 1));
        $this->db->where('id_parent',$param);
        return $this->db->get()->result_array();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_alokasi_anggaran_covid_model.php */
/* Location: ./application/models/M_alokasi_anggaran_covid_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-27 16:41:58 */
/* http://harviacode.com */