<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_apbn_covid_alokasi_model extends CI_Model
{

    public $table = 'm_apbn_covid_alokasi';
    public $id = 'id_alokasi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get('v_apbn_covid_alokasi')->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get('v_apbn_covid_alokasi')->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_alokasi', $q);
        $this->db->or_like('nama_kegiatan', $q);
        $this->db->or_like('nama_satker', $q);
        $this->db->or_like('volume', $q);
        $this->db->or_like('alokasi', $q);
        $this->db->or_like('created_by', $q);
        $this->db->or_like('created_date', $q);
        $this->db->from('v_apbn_covid_alokasi');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_alokasi', $q);
        $this->db->or_like('nama_kegiatan', $q);
        $this->db->or_like('nama_satker', $q);
        $this->db->or_like('volume', $q);
        $this->db->or_like('alokasi', $q);
        $this->db->or_like('created_by', $q);
        $this->db->or_like('created_date', $q);
        $this->db->limit($limit, $start);
        return $this->db->get('v_apbn_covid_alokasi')->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file M_apbn_covid_alokasi_model.php */
/* Location: ./application/models/M_apbn_covid_alokasi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-27 16:23:12 */
/* http://harviacode.com */