<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_satker_model extends CI_Model
{

    public $table = 'm_satker';
    public $id = 'id_satker';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_satker', $q);
	$this->db->or_like('id_satker_jenis', $q);
	$this->db->or_like('id_provinsi', $q);
	$this->db->or_like('id_kota_kabupaten', $q);
	$this->db->or_like('id_rumah_sakit', $q);
	$this->db->or_like('kode_satker', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('updated_by', $q);
	$this->db->or_like('updated_date', $q);
	$this->db->or_like('isdeleted', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_satker', $q);
	$this->db->or_like('id_satker_jenis', $q);
	$this->db->or_like('id_provinsi', $q);
	$this->db->or_like('id_kota_kabupaten', $q);
	$this->db->or_like('id_rumah_sakit', $q);
	$this->db->or_like('kode_satker', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('updated_by', $q);
	$this->db->or_like('updated_date', $q);
	$this->db->or_like('isdeleted', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_satker_model.php */
/* Location: ./application/models/M_satker_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-09-24 09:21:55 */
/* http://harviacode.com */