<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_satker_model extends CI_Model
{

    public $table = 'm_satker';
    public $id = 'id_satker';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_satker,id_jenis_satker,id_provinsi,id_kota_kabupaten,id_rumah_sakit,kode_satker,nama,created_by,created_date,updated_by,updated_date,isdeleted');
        $this->datatables->from('m_satker');
        //add this line for join
        //$this->datatables->join('table2', 'm_satker.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('m_satker/read/$1'),'<i class="fal fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm waves-effect waves-themed'))." 
            ".anchor(site_url('m_satker/update/$1'),'<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm waves-effect waves-themed'))." 
                ".anchor(site_url('m_satker/delete/$1'),'<i class="fal fa-trash" aria-hidden="true"></i>','class="btn btn-danger btn-sm waves-effect waves-themed" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_satker');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_satker', $q);
	$this->db->or_like('id_jenis_satker', $q);
	$this->db->or_like('id_provinsi', $q);
	$this->db->or_like('id_kota_kabupaten', $q);
	$this->db->or_like('id_rumah_sakit', $q);
	$this->db->or_like('kode_satker', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('updated_by', $q);
	$this->db->or_like('updated_date', $q);
	$this->db->or_like('isdeleted', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_satker', $q);
	$this->db->or_like('id_jenis_satker', $q);
	$this->db->or_like('id_provinsi', $q);
	$this->db->or_like('id_kota_kabupaten', $q);
	$this->db->or_like('id_rumah_sakit', $q);
	$this->db->or_like('kode_satker', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('updated_by', $q);
	$this->db->or_like('updated_date', $q);
	$this->db->or_like('isdeleted', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_satker_model.php */
/* Location: ./application/models/M_satker_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-15 15:34:44 */
/* http://harviacode.com */