<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_sub_kegiatan_anggaran_covid_model extends CI_Model
{

    public $table = 'm_sub_kegiatan_anggaran_covid';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama_sub_kegiatan', $q);
	$this->db->or_like('create_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->select('m_sub_kegiatan_anggaran_covid.*,m_kegiatan_anggaran_covid.nama_kegiatan');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('m_sub_kegiatan_anggaran_covid.id', $q);
	$this->db->or_like('nama_sub_kegiatan', $q);
	$this->db->or_like('create_date', $q);
    $this->db->join('m_kegiatan_anggaran_covid','m_kegiatan_anggaran_covid.id = '.$this->table.'.id_kegiatan','left');
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_sub_kegiatan_anggaran_covid_model.php */
/* Location: ./application/models/M_sub_kegiatan_anggaran_covid_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-09-16 04:37:17 */
/* http://harviacode.com */