<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Rencana_masalah_anggaran_covid_model extends CI_Model
{

    public $table = 'rencana_masalah_anggaran_covid';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_alokasi', $q);
	$this->db->or_like('rencana_penarikan_dana', $q);
	$this->db->or_like('rencana_penarikan_dana_sd', $q);
	$this->db->or_like('permasalahan', $q);
	$this->db->or_like('rencana_tindak_lanjut', $q);
	$this->db->or_like('create_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL,$id_alokasi=NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('id_alokasi',$id_alokasi);
 //        $this->db->like('id', $q);
	// $this->db->or_like('id_alokasi', $q);
	// $this->db->or_like('rencana_penarikan_dana', $q);
	// $this->db->or_like('rencana_penarikan_dana_sd', $q);
	// $this->db->or_like('permasalahan', $q);
	// $this->db->or_like('rencana_tindak_lanjut', $q);
	// $this->db->or_like('create_date', $q);
	// $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function get_last($id_alokasi){
        $sql = $this->db->query("select rencana_penarikan_dana_sd from rencana_masalah_anggaran_covid where id_alokasi =".$id_alokasi." order by id DESC limit 1;");
        $data = $sql->result_array();
        
        if(!empty($data))
           return $data[0]['rencana_penarikan_dana_sd'];
        else
            return true;
    }

}

/* End of file Rencana_masalah_anggaran_covid_model.php */
/* Location: ./application/models/Rencana_masalah_anggaran_covid_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-09-02 21:13:42 */
/* http://harviacode.com */