<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_apbn_covid_realisasi_model extends CI_Model
{

    public $table = 't_apbn_covid_realisasi';
    public $id = 'id_realisasi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data realisasi by satker
    function get_realisasi($id_alokasi)
    {
        $this->db->from('v_apbn_covid_realisasi');
        $this->db->where('id_alokasi', $id_alokasi);
        $this->db->order_by('created_date', 'ASC');
        return $this->db->get()->result();
    }

    // get data alokasi by id alokasi
    function get_alokasi_id($id_alokasi)
    {
        $this->db->from('v_apbn_covid_alokasi');
        $this->db->where('id_alokasi', $id_alokasi);
        $this->db->order_by('created_date', 'ASC');
        return $this->db->get()->result();
    }

    // get data alokasi by satker
    function get_alokasi($kode_satker)
    {
        $this->db->from('v_apbn_covid_alokasi');
        $this->db->where('kode_satker', $kode_satker);
        $this->db->order_by('created_date', 'ASC');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_realisasi', $q);
        $this->db->or_like('id_alokasi', $q);
        $this->db->or_like('volume', $q);
        $this->db->or_like('realisasi_persen', $q);
        $this->db->or_like('realisasi_nilai', $q);
        $this->db->or_like('id_rincian_hambatan', $q);
        $this->db->or_like('tindak_lanjut', $q);
        $this->db->or_like('created_by', $q);
        $this->db->or_like('created_date', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_realisasi', $q);
        $this->db->or_like('id_alokasi', $q);
        $this->db->or_like('volume', $q);
        $this->db->or_like('realisasi_persen', $q);
        $this->db->or_like('realisasi_nilai', $q);
        $this->db->or_like('id_rincian_hambatan', $q);
        $this->db->or_like('tindak_lanjut', $q);
        $this->db->or_like('created_by', $q);
        $this->db->or_like('created_date', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file T_apbn_covid_realisasi_model.php */
/* Location: ./application/models/T_apbn_covid_realisasi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-27 16:56:04 */
/* http://harviacode.com */