<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_dak_menu_kegiatan_model extends CI_Model
{

    public $table = 't_dak_menu_kegiatan';
    public $id = 'id_menu_kegiatan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('id_menu_kegiatan,id_dak_komponen_sub,id_dak_alokasi,nama_menu_kegiatan,created_by,created_date,updated_by,updated_date,isdeleted');
        $this->datatables->from('t_dak_menu_kegiatan');
        //add this line for join
        //$this->datatables->join('table2', 't_dak_menu_kegiatan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('t_dak_menu_kegiatan/read/$1'), '<i class="fal fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm waves-effect waves-themed')) . "
            " . anchor(site_url('t_dak_menu_kegiatan/update/$1'), '<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm waves-effect waves-themed')) . "
                " . anchor(site_url('t_dak_menu_kegiatan/delete/$1'), '<i class="fal fa-trash" aria-hidden="true"></i>', 'class="btn btn-danger btn-sm waves-effect waves-themed" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_menu_kegiatan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    function get_rincian($idsubkomponen, $idalokasi)
    {
        $this->db->select('*');
        $this->db->from('v_rincian');
        $this->db->where('id_dak_alokasi', $idalokasi);
        $this->db->where('id_dak_komponen_sub', $idsubkomponen);
        return $this->db->get()->result();
    }


    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_menu_kegiatan', $q);
        $this->db->or_like('id_dak_komponen_sub', $q);
        $this->db->or_like('id_dak_alokasi', $q);
        $this->db->or_like('nama_menu_kegiatan', $q);
        $this->db->or_like('created_by', $q);
        $this->db->or_like('created_date', $q);
        $this->db->or_like('updated_by', $q);
        $this->db->or_like('updated_date', $q);
        $this->db->or_like('isdeleted', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_menu_kegiatan', $q);
        $this->db->or_like('id_dak_komponen_sub', $q);
        $this->db->or_like('id_dak_alokasi', $q);
        $this->db->or_like('nama_menu_kegiatan', $q);
        $this->db->or_like('created_by', $q);
        $this->db->or_like('created_date', $q);
        $this->db->or_like('updated_by', $q);
        $this->db->or_like('updated_date', $q);
        $this->db->or_like('isdeleted', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file T_dak_menu_kegiatan_model.php */
/* Location: ./application/models/T_dak_menu_kegiatan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-22 16:23:50 */
/* http://harviacode.com */